config/routes.rb
Brandometer::Application.routes.draw do

  resources :users, except: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :brands
  resources :tags, only: [:create]
  resources :ratings, only: [:create]
  resources :battles, only: [:create]

  root to: 'static_pages#home'

  match '/test',    to: 'tests#index'

  match '/signup',  to: 'users#new'
  match '/finish',  to: 'users#additional_info'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/tag',    to: 'tags#new', via: :get
  match '/tag/:id',to: 'tags#new'

  match '/rate',    to: 'ratings#new', via: :get
  match '/rate/:id',to: 'ratings#new'

  match '/battle', to: 'battles#new', via: :get
  match '/battle/:brand1/:brand2', to: 'battles#new'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
%h1= t('.h1')

app/views/static_pages/contact.html.haml
%h1= t('.h1')

app/views/static_pages/home.html.haml
.center.hero-unit
  - if signed_in?
    %h1 Brand-o-meter
    %h2= t('.h2')
    %p
      Begin by either
      = link_to "tagging", tag_path
      or
      = link_to "rating", rate_path
      a brand. Or let them
      = link_to "battle", battle_path
      it out!
  - else
    %h1= t('.h1')
    %h2= t('.h2')
    = link_to t('.signupnow'), signup_path, class: "btn btn-large btn-primary"
.row
  .span4.action-box
    %a{ href: tag_path }
      .icon-holder
        %i.icon-tag
      .action= t('.tag')
  .span4.action-box
    %a{ href: rate_path }
      .icon-holder
        %i.icon-star
      .action= t('.rate')
  .span4.action-box
    %a{ href: battle_path }
      .icon-holder
        %i.icon-fire
      .action= t('.battle')