config/routes.rb
Brandometer::Application.routes.draw do

  resources :users, except: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :brands
  resources :tags, only: [:create]
  resources :ratings, only: [:create]
  resources :battles, only: [:create]

  root to: 'static_pages#home'

  match '/test',    to: 'tests#index'

  match '/signup',  to: 'users#new'
  match '/finish',  to: 'users#additional_info'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/tag',    to: 'tags#new', via: :get
  match '/tag/:id',to: 'tags#new'

  match '/rate',    to: 'ratings#new', via: :get
  match '/rate/:id',to: 'ratings#new'

  match '/battle', to: 'battles#new', via: :get
  match '/battle/:brand1/:brand2', to: 'battles#new'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :name, :uid, :active, :collecting, :elo, :wr

  has_many :tag_occurrences
  has_many :tags, through: :tag_occurrences
  has_many :ratings

  before_save :cleanup_name
  before_save :create_uid

  validates :name, presence: true
  validates :uid, uniqueness: true

  scope :battles

  HUMANIZED_ATTRIBUTES = {
    uid: "Unique identifier"
  }

  def to_param
    "#{self.uid.parameterize}"
  end

  def self.human_attribute_name(attribute, options = {})
    HUMANIZED_ATTRIBUTES[attribute.to_sym] || super
  end

  def rating
    return 0 unless ratings.any?
    ((ratings.sum(:value).to_f / ratings.size.to_f) * 100).round / 100.00
  end

  def battles
    Battle.where("loser = ? OR winner = ?", id, id)
  end

  def battles_lost
    Battle.where("loser = ?", id)
  end

  def battles_won
    Battle.where("winner = ?", id)
  end

  private

    def cleanup_name
      self.name = self.name.gsub(/\s\s+/, ' ')
    end

    def create_uid
      self.uid ||= name
      self.uid = self.uid.mb_chars.normalize(:kd).gsub(/[^\x00-\x7F]/, '').downcase.to_s.gsub(/ /, '_')
    end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  before_filter :signed_in_user, except: [:show]
  before_filter :admin_user, except: [:show]

  def index
    @brands = Brand.order("name").paginate(page: params[:page])
  end

  def show
    @brand = Brand.find_by_uid(params[:id])
  end

  def new
    @brand = Brand.new
  end

  def edit
    @brand = Brand.find_by_uid(params[:id])
  end

  def update
    @brand = Brand.find_by_uid(params[:id])
    if @brand.update_attributes(params[:brand])
      flash[:success] = "Brand updated"
      redirect_to @brand
    else
      render 'edit'
    end
  end

  def create
    params[:brand].delete(:uid) if params[:brand][:uid].empty?

    @brand = Brand.new(params[:brand])
    if @brand.save
      flash[:success] = "Created brand: #{@brand.name}"
      redirect_to new_brand_path
    else
      render 'new'
    end
  end

  def destroy
    brand = Brand.find_by_uid(params[:id]).destroy
    flash[:success] = "Brand '#{brand.name}' destroyed."
    redirect_to brands_path
  end

end

app/helpers/brands_helper.rb
module BrandsHelper

  def random_brand
    Brand.first(order: "RANDOM()")
  end

  def random_brand_path(exclude = nil)
    random_brand_uid = Brand.where("NOT id = ?", exclude ? exclude : 0).first(order: "RANDOM()").uid
    { action: "new", id: random_brand_uid }
  end

  def logotype_for(brand, options = {})
    image_tag("logotypes/#{brand.uid}_logotype.png", options.merge({ class: "brand-logotype" }))
  end

  def votes_for(brand)
    content_tag(:small, "(#{brand.ratings.size} votes)")
  end

  def rating_for(brand)
    midpoint = 200
    bar = content_tag(:div, brand.rating, class: "ir rating-bar rating-#{rating_grade(brand.rating)}", style: "width: #{brand.rating * midpoint + midpoint}px;")
    content_tag(:div, bar, class: "rating-bar-container")
  end

  def rating_grade(rating)
    case rating
    when -1..-0.3
      "bad"
    when -0.3..0.3
      "alright"
    when 0.3..1
      "good"
    end
  end

  def tag_cloud_for(brand)
    # Put all unique tags in a hash and count them individually
    tags = {}
    brand.tags.each do |t|
      key = t.value
      unless tags.include?(key)
        tags[key] = 1 unless key.empty?
      else
        tags[key] += 1
      end
    end

    # Convert tags hash to array and sort it on tag counts
    tags = tags.to_a.sort { |a, b| a[1] <=> b[1] }

    # Create tag cloud markup from a center weighted array
    content_tag(:div, create_cloud(center_weight(tags)), class: "tag-cloud").html_safe
  end

  def create_cloud(tags)
    cloud = ''
    tags.each do |key, value|
      cloud += content_tag(:span, key, style: "font-size: #{( 1 + (value - 1) * 0.4 )}em")
    end
    cloud.html_safe
  end

  # Takes an array (sorted from lowest to highest), and rearranges it to have the largest
  # value in the center and the rest going down to the right and left.
  # Example: [0, 1, 2, 3, 4, 5, 6] --> [1, 3, 5, 6, 4, 2, 0]
  def center_weight(a)
    centered_array = Array.new(a.size)
    pos = -1
    count = 0

    a.each do |item| centered_array[pos] = item
      count += 1
      pos < 0 ? pos += count : pos -= count
    end

    return centered_array
  end


end

app/views/brands/_brand.html.haml
%li
  = link_to brand.name, brand
  - if current_user.admin?
    |
    = link_to 'Edit', edit_brand_path(brand)
    |
    = link_to 'Delete', brand, method: :delete, confirm: 'Are you sure?'

app/views/brands/edit.html.haml
- provide(:title, "Edit #{@brand.name}")
%h1= "Update #{@brand.name}"
.row
  .span6.offset3
    = form_for(@brand) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :name
      = f.text_field :name

      = f.label :uid, 'Unique identifier (permalink)'
      = f.text_field :uid

      .checkbox-group
        %label.checkbox{ for: 'brand_active'}
          = f.check_box :active
          Active
        %label.checkbox{ for: 'brand_collecting'}
          = f.check_box :collecting
          Collecting

      = f.label :elo, 'ELO Rating'
      = f.text_field :elo, disabled: true

      = f.submit 'Save changes', class: 'btn btn-large btn-primary'

app/views/brands/index.html.haml
- provide(:title, 'All brands')
%h1 All brands

%ul.brands
  = render @brands

= will_paginate

app/views/brands/new.html.haml
- provide(:title, 'Create new brand')
%h1 Create new brand

.row
  .span6.offset3
    = form_for(@brand) do |f|
      = render 'shared/error_messages', object: f.object

      = f.label :name
      = f.text_field :name, autofocus: 'autofocus'

      = f.label :uid, 'Unique identifier (permalink)'
      = f.text_field :uid

      = f.submit 'Create brand', class: 'btn btn-large btn-primary'

app/views/brands/show.html.haml
- provide(:title, @brand.name)
.row
  %aside.span4
    %section
      %h1= @brand.name
      = logotype_for(@brand)
  .span8
    %h2 Tag cloud
    = tag_cloud_for(@brand)
    %h2= "Rating #{votes_for(@brand)}".html_safe
    = rating_for(@brand)