config/routes.rb
Brandometer::Application.routes.draw do

  resources :users, except: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :brands
  resources :tags, only: [:create]
  resources :ratings, only: [:create]
  resources :battles, only: [:create]

  root to: 'static_pages#home'

  match '/test',    to: 'tests#index'

  match '/signup',  to: 'users#new'
  match '/finish',  to: 'users#additional_info'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/tag',    to: 'tags#new', via: :get
  match '/tag/:id',to: 'tags#new'

  match '/rate',    to: 'ratings#new', via: :get
  match '/rate/:id',to: 'ratings#new'

  match '/battle', to: 'battles#new', via: :get
  match '/battle/:brand1/:brand2', to: 'battles#new'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{ href: '/' } Brand-o-meter
    = t('.copyright')
  %nav
    %ul
      %li= link_to t('.about'), about_path
      %li= link_to t('.contact'), contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "Brand-o-meter", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          %li= link_to icon_label("tag", t('.tag')), tag_path
          %li= link_to icon_label("star", t('.rate')), rate_path
          %li= link_to icon_label("fire", t('.battle')), battle_path
          - if signed_in?
            %li#fat-menu.dropdown
              %a.dropdown-toggle{ href: '#', data: { toggle: 'dropdown' }}
                = t('.account')
                %b.caret
              %ul.dropdown-menu
                %li
                  %span= icon_label('user', current_user.name)
                %li
                  = link_to icon_label('cog', t('.settings')), edit_user_path(current_user)
                %li.divider
                %li
                  = link_to icon_label('signout', t('.signout')), signout_path, method: 'delete'
            - if current_user.admin?
              %li#admin-menu.dropdown
                %a.dropdown-toggle{ href: '#', data: { toggle: 'dropdown' }}
                  = icon_label('lock', 'Admin')
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to icon_label('th-list', 'List all brands'), brands_path
                  %li= link_to icon_label('plus', 'Create new brand'), new_brand_path
                  %li.divider
                  %li= link_to icon_label('user', 'List all users'), users_path
          - else
            %li= link_to icon_label('signin', t('.signin')), signin_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?